runtime: nodejs
env: flex

env_variables:
  SQL_USER: root
  SQL_PASSWORD: root
  INSTANCE_CONNECTION_NAME: trienekens-deploy:asia-southeast1:trienekensdeploy
beta_settings:
  cloud_sql_instances: trienekens-deploy:asia-southeast1:trienekensdeploy
  GCLOUD_STORAGE_BUCKET: trienekens-management-images