runtime: nodejs
env: flex

env_variables:
  DATABASE_USER: root
  DATABASE_PASSWORD: root
  DATABASE_HOST: 35.197.149.184
  DATABASE_NAME: dbtrienekens
  SERVER_PORT: 8080
  INSTANCE_CONNECTION_NAME: trienekens-management-portal:asia-southeast1:trienekens
  GCLOUD_STORAGE_BUCKET: trienekens-management-portal-images
beta_settings:
  cloud_sql_instances: trienekens-management-portal:asia-southeast1:trienekens
  
network:
  session_affinity: true
  
