runtime: nodejs
env: flex

env_variables:
  DATABASE_USER: root
  DATABASE_PASSWORD: root
  DATABASE_HOST: 35.240.138.167
  DATABASE_NAME: dbtrienekens
  SERVER_PORT: 3000
  INSTANCE_CONNECTION_NAME: trienekens-management:asia-southeast1:trienekens
beta_settings:
  cloud_sql_instances: trienekens-management:asia-southeast1:trienekens
network:
  session_affinity: true